name = "cloudflare-worker-qryn"
main = "src/index.js"
account_id = ""
workers_dev = true
usage_model = "unbound"
compatibility_date = "2022-08-01"

[vars]
lokiHost = "https://localhost:3100/loki/api/v1/push"
